# Generated by Django 4.2.16 on 2024-11-08 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RASA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удален')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ApplicationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_main', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RASA.application')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RASA.service')),
            ],
            options={
                'unique_together': {('application', 'service')},
            },
        ),
    ]
