# Generated by Django 5.1.3 on 2024-11-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acceptance',
            table='acceptance',
        ),
    ]
