# Generated by Django 5.1.3 on 2024-12-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0002_alter_acceptance_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('deleted', 'Удалён')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
