# Generated by Django 5.1.3 on 2025-02-09 09:39

import RASA.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', RASA.models.NewUserManager()),
            ],
        ),
    ]
