# Generated by Django 5.1.3 on 2024-12-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0003_engine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('deleted', 'Удалён')], default='active', max_length=20),
        ),
    ]
