# Generated by Django 5.1.3 on 2025-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0004_alter_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='total_accepted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
