# Generated by Django 5.1.3 on 2024-12-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0004_alter_engine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='engineacceptance',
            name='accepted',
            field=models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Не принято')], default='accepted', max_length=20),
        ),
    ]
