# Generated by Django 5.1.3 on 2025-02-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0005_acceptance_total_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
