# Generated by Django 5.1.3 on 2025-02-12 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0006_acceptance_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='EngineAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RASA.attribute')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RASA.engine')),
            ],
            options={
                'unique_together': {('engine', 'attribute')},
            },
        ),
    ]
