# Generated by Django 5.1.3 on 2025-02-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0007_attribute_engineattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineattribute',
            name='value',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='engineattribute',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='RASA.engine'),
        ),
    ]
