# Generated by Django 5.1.3 on 2025-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RASA', '0008_engineattribute_value_alter_engineattribute_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
